name:                rollbar
version:             2.1.1
synopsis:            error tracking through rollbar.com
homepage:            https://github.com/flipstone/rollbar-haskell
license:             MIT
author:              Flipstone Technology Partners
maintainer:          development@flipstone.com
copyright:           Daggerboard Inc. makers of docmunch.com, Azara Solutions Inc.
category:            Logging

default-extensions:
- OverloadedStrings
ghc-options:
- -Wall
- -Werror
- -Wcpp-undef
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-orphans
dependencies:
  - base >=4.6 && < 5
  - text >=1.2 && < 2.1
  - aeson >=1.2 && < 2.2
  - vector >=0.12 && < 0.14
  - network >=2.6 && < 3.2
  - monad-control >=1.0.2 && < 1.0.4
  - resourcet >=1.1 && < 1.4
  - http-conduit >=2.2 && < 2.4
  - lifted-base == 0.2.3.*
  - network-bsd == 2.8.*

library:
  source-dirs: src
  exposed-modules:
  - Rollbar
  - Rollbar.MonadLogger
